---
- hosts: all
  become: yes

  vars:
    username: "student"
    hostname: "so-vm"
    interface: "gui"

  tasks:

  - name: update apt cache on ubuntu
    become: true
    apt:
      update_cache: yes

  - name: Basic setup
    include: ../playbooks-common/basic.yml

  - name: Install dependencies
    include: ../playbooks-common/dependencies.yml

  - name: Reboot the machine
    reboot:

  - name: Dev-tools setup
    include: ../playbooks-common/dev-tools.yml

  - name: Docker setup
    include: ../playbooks-common/docker.yml

  - name: Ltrace setup
    include: ../playbooks-common/ltrace.yml

  - name: D setup
    include: ../playbooks-common/dlang.yml

  - name: Java setup
    include: ../playbooks-common/java.yml

  - name: SO repo setup
    include: ../playbooks-common/utils.yml

  - name: Dev-tools setup
    include: dev-tools.yml

  - name: VSCode setup
    include: ../playbooks-common/vscode.yml

  - name: Basic setup
    include: ../playbooks-common/allow_ssh.yml 

  handlers:
  - name: restart_sshd
    service:
      name: sshd
      state: restarted